apiVersion: monitor.azure.com/v1
kind: Instrumentation
metadata:
  name: otel-demo-instrumentation
  namespace: otel-demo
spec:
  destination:
    applicationInsightsConnectionString: "__APP_INSIGHTS_CONNECTION_STRING__"
  settings:
    autoInstrumentationPlatforms: []
