apiVersion: monitor.azure.com/v1
kind: Instrumentation
metadata:
  name: otel-demo-instrumentation
  namespace: otel-demo
spec:
  destination:
    applicationInsightsConnectionString: "InstrumentationKey=728f8f23-0f17-4757-96b0-e67d5c0ea13d;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/;LiveEndpoint=https://westus2.livediagnostics.monitor.azure.com/;ApplicationId=e4580258-7369-47ea-a880-d85e204cfe5d"
  settings:
    autoInstrumentationPlatforms: []
